### ISSUE TITLE
controller service account lacks permissions to interact with k8s network policies

### ISSUE THREAD

**Issue by keriwarr** [GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang#26]
Hey all, Thanks for this tool!

When I create a FQDN network policy, the controller-manager pod logs the following error:
```
failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:fqdnnetworkpolicies-system:fqdnnetworkpolicies-controller-manager" cannot list resource "networkpolicies" in API group "networking.k8s.io" at the cluster scope
```

I was able to work around this by adding the following rule to the `fqdnnetworkpolicies-manager-role` `ClusterRole`:

```
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

I'm running this on a fresh GKE cluster (created from the UI) with:
- version 1.25.6-gke.1000
- dataplane v2
- NodeLocal DNS cache
- otherwise default settings

Have I made a mistake somewhere?
